name: e_imar_mobile
description: Premium Flutter E-İmar & Emsal Sorgu mobile foundation.
publish_to: none

version: 0.1.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
